name: iOS native E2E

on:
  pull_request:
    branches: ['main']

jobs:
  build_ios_for_e2e:
    type: build
    params:
      platform: ios
      profile: e2e-test

  maestro_ios:
    needs: [build_ios_for_e2e]
    type: maestro
    params:
      build_id: ${{ needs.build_ios_for_e2e.outputs.build_id }}
      flow_path: .maestro
      shards: 2
      retries: 1
      retry_failed_only: true
      record_screen: true
      maestro_version: 2.6.1
      device_identifier: iPhone 16 Plus
